teamvault/apps/secrets/api/urls.py
from django.urls import path

from .views import (
    SecretDetail,
    SecretList,
    SecretRevisionDetail,
    SecretShare,
    SecretShareDetail,
    UserPendingSecretsList,
    data_get,
    generate_password_view,
    otp_get,
)

urlpatterns = (
    path(
        'secrets/',
        SecretList.as_view(),
        name='api.secret_list',
    ),
    path(
        'users/<str:username>/pending-secrets/',
        UserPendingSecretsList.as_view(),
        name='api.user-pending-secrets',
    ),
    path(
        'secrets/<str:hashid>/',
        SecretDetail.as_view(),
        name='api.secret_detail',
    ),
    path(
        'secrets/<str:hashid>/shares/',
        SecretShare.as_view(),
        name='api.secret_share',
    ),
    path(
        'secrets/<str:hashid>/shares/<int:pk>',
        SecretShareDetail.as_view(),
        name='api.secret_share_detail',
    ),
    path(
        'secret-revisions/<str:hashid>/',
        SecretRevisionDetail.as_view(),
        name='api.secret-revision_detail',
    ),
    path(
        'secret-revisions/<str:hashid>/data',
        data_get,
        name='api.secret-revision_data',
    ),
    path(
        'secret-revisions/<str:hashid>/data/otp',
        otp_get,
        name='api.secret-revision_otp',
    ),
    path(
        'generate_password/',
        generate_password_view,
        name='api.generate-password',
    ),
)

teamvault/apps/secrets/urls.py
from django.urls import path

from . import views

urlpatterns = (
    path(
        '',
        views.dashboard,
        name='dashboard',
    ),
    path(
        'opensearch.xml',
        views.opensearch,
        name='opensearch',
    ),
    path(
        'secrets/',
        views.secret_list,
        name='secrets.secret-list',
    ),
    path(
        'secrets/<str:hashid>/',
        views.secret_detail,
        name='secrets.secret-detail',
    ),
    path(
        'secrets/<str:hashid>/delete',
        views.secret_delete,
        name='secrets.secret-delete',
    ),
    path(
        'secrets/<str:hashid>/download',
        views.secret_download,
        name='secrets.secret-download',
    ),
    path(
        'secrets/<str:hashid>/edit',
        views.secret_edit,
        name='secrets.secret-edit',
    ),
    path(
        'secrets/<str:hashid>/revisions',
        views.secret_revisions,
        name='secrets.secret-revisions',
    ),
    path(
        'secrets/<str:hashid>/changes/<str:change_hashid>/delete',
        views.secret_change_delete,
        name='secrets.secret-change-delete',
    ),
    path(
        'revisions/<str:revision_hashid>/',
        views.secret_revision_detail,
        name='secrets.revision-detail',
    ),
    path(
        'revisions/<str:revision_hashid>/download/',
        views.secret_revision_download,
        name='secrets.revision-download',
    ),
    path(
        '<str:secret_hashid>/revisions/<str:revision_hashid>/restore/',
        views.restore_secret_revision,
        name='restore_secret_revision',
    ),
    path(
        'secrets/<str:hashid>/metadata',
        views.secret_metadata,
        name='secrets.secret-metadata',
    ),
    path(
        'secrets/<str:hashid>/restore',
        views.secret_restore,
        name='secrets.secret-restore',
    ),
    path(
        'secrets/<str:hashid>/share',
        views.secret_share_list,
        name='secrets.secret-share',
    ),
    path(
        'secrets/<str:hashid>/share/<int:share_id>/delete',
        views.secret_share_delete,
        name='secrets.secret-share-delete',
    ),
    path(
        'secrets/add/<str:content_type>',
        views.secret_add,
        name='secrets.secret-add',
    ),
    path(
        'secrets/live-search',
        views.secret_search,
        name='secrets.secret-search',
    ),
)

teamvault/urls.py
from django.conf.urls import include
from django.urls import path

handler404 = 'teamvault.views.handler404'

urlpatterns = (
    path('api/', include('teamvault.apps.secrets.api.urls'), name='api'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('audit', include('teamvault.apps.audit.urls'), name='audit'),
    path('', include('teamvault.apps.secrets.urls'), name='secrets'),
    path('', include('teamvault.apps.accounts.urls'), name='accounts'),
    path('', include('social_django.urls', namespace='social')),
)

teamvault/apps/secrets/forms.py
from datetime import date

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError
from django.forms.widgets import RadioSelect
from django.utils.translation import gettext_lazy as _

from teamvault.apps.secrets.enums import AccessPolicy
from .models import Secret, SharedSecretData
from .utils import extract_url_and_params
from .validators import is_valid_otp_secret

User = get_user_model()

GENERIC_FIELDS_HEADER = ['name']
GENERIC_FIELDS_FOOTER = [
    'access_policy',
    'description',
    'grant_description',
    'needs_changing_on_leave',
    'shared_groups_on_create',
]


class SecretForm(forms.ModelForm):
    access_policy = forms.TypedChoiceField(
        choices=AccessPolicy.choices,
        coerce=int,
        initial=AccessPolicy.DISCOVERABLE,
        widget=RadioSelect(),
    )
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'cols': '15', 'rows': '4'}))
    needs_changing_on_leave = forms.BooleanField(
        help_text=_("This secret will be marked as 'needs changing' when a user who accessed it is deactivated."),
        initial=True,
        label=_('Needs changing'),
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    )
    shared_groups_on_create = forms.ModelMultipleChoiceField(
        help_text=_('Default groups you configured in your settings will be selected automatically.'),
        label=_('Share with groups'),
        queryset=Group.objects.all().order_by('name'),
        required=False,
    )
    grant_description = forms.CharField(
        label=_('Reason'),
        required=False,  # see clean() below
        widget=forms.Textarea(attrs={'cols': '15', 'rows': '2'}),
    )

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['shared_groups_on_create'] and not cleaned_data['grant_description']:
            self.add_error(
                'grant_description',
                _('Please provide a valid reason to share this secret with the groups selected above.'),
            )


class CCForm(SecretForm):
    expiration_month = forms.IntegerField(
        min_value=1,
        max_value=12,
    )
    expiration_year = forms.IntegerField(
        min_value=date.today().year,
        max_value=date.today().year + 50,
    )
    holder = forms.CharField(
        label=_('Name on card'),
    )
    number = forms.CharField()
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput,
    )
    security_code = forms.CharField(
        label=_('Card CVV'),
        required=False,
        widget=forms.NumberInput,
    )

    class Meta:
        model = Secret
        fields = (
            GENERIC_FIELDS_HEADER
            + [
                'expiration_month',
                'expiration_year',
                'holder',
                'number',
                'password',
                'security_code',
            ]
            + GENERIC_FIELDS_FOOTER
        )


class FileForm(SecretForm):
    file = forms.FileField(
        # Note: There's also custom handling for files with a file size above the FILE_UPLOAD_MAX_MEMORY_SIZE limit
        #  in the corresponding view
        allow_empty_file=False,
        required=False,
    )

    class Meta:
        model = Secret
        fields = GENERIC_FIELDS_HEADER + ['file'] + GENERIC_FIELDS_FOOTER


class PasswordForm(SecretForm):
    otp_key = forms.CharField(required=False)
    otp_key_data = forms.CharField(
        required=False,
    )
    password = forms.CharField(
        required=False,
    )
    url = forms.CharField(
        max_length=255,
        required=False,
        label='URL',
    )
    username = forms.CharField(
        max_length=255,
        required=False,
    )

    def clean_password(self):
        if self.instance.pk is None and not self.cleaned_data['password']:
            # password is only required when adding a new secret
            raise forms.ValidationError(_('Please enter a password.'))
        return self.cleaned_data['password']

    def clean_otp_key_data(self):
        cleaned_otp_key_data = self.cleaned_data['otp_key_data']
        if self.instance.pk is not None and not cleaned_otp_key_data:
            return cleaned_otp_key_data

        try:
            _as_url, data_params = extract_url_and_params(cleaned_otp_key_data)
        except Exception as exc:
            raise forms.ValidationError(
                _('OTP key should have a format like this: ___?secret=___&digits=___ ...')
            ) from exc
        secret = data_params.get('secret', '')
        is_valid_otp_secret(secret)
        return cleaned_otp_key_data

    class Meta:
        model = Secret
        fields = GENERIC_FIELDS_HEADER + ['password', 'username', 'url'] + GENERIC_FIELDS_FOOTER


class SecretShareForm(forms.ModelForm):
    group = forms.ModelChoiceField(
        required=False,
        queryset=Group.objects.none(),  # will be set in view
    )

    user = forms.ModelChoiceField(
        required=False,
        queryset=User.objects.none(),  # will be set in view
    )

    grant_description = forms.CharField(
        label=_('Reason'), required=True, widget=forms.Textarea(attrs={'cols': '15', 'rows': '2'})
    )

    granted_until = forms.DateTimeField(
        required=False,
        widget=forms.DateTimeInput(),
    )

    def clean(self):
        cleaned_data = super().clean()
        if (cleaned_data['group'] and cleaned_data['user']) or (not cleaned_data['group'] and not cleaned_data['user']):
            raise ValidationError('Choose exactly one group *or* one user to share the secret with.')

    class Meta:
        fields = ['group', 'user', 'granted_until', 'grant_description']
        model = SharedSecretData

teamvault/apps/secrets/templates/secrets/addedit_content/cc.html
{% extends "secrets/secret_addedit.html" %}
{% load django_bootstrap5 %}
{% load i18n %}
{% block content_type_fields %}
    <div class="row">
        <div class="col-12 col-lg-7" id="ccform">
            {% bootstrap_field form.number placeholder='Credit card number' layout='horizontal' horizontal_label_class="col-lg-3" horizontal_field_class="col-lg-7" %}
            {% bootstrap_field form.holder placeholder='Card holder' layout='horizontal' horizontal_label_class="col-lg-3" horizontal_field_class="col-lg-7" %}

            <div class="row mb-3 required">
                <label class="col-lg-3 col-form-label" for="id_expiration_month">{% trans "Expiration date" %}</label>
                <div class="col-lg-7">
                    <div class="input-group">
                        <input type="text"
                               class="form-control text-center {% if form.expiration_month.errors %}is-invalid{% elif form.expiration_month.form.is_bound %}is-valid{% endif %}"
                               name="expiration_month" id="id_expiration_month" required="required" maxlength="2"
                               size="2" placeholder="{% translate "MM" %}"
                               value="{{ form.expiration_month.value|default_if_none:"" }}">
                        <div class="vr mx-3"></div>
                        <input type="text"
                               class="form-control text-center {% if form.expiration_year.errors %}is-invalid{% elif form.expiration_year.form.is_bound %}is-valid{% endif %}"
                               name="expiration_year" id="id_expiration_year" required="required" maxlength="4" size="4"
                               placeholder="{% translate "YYYY" %}"
                               value="{{ form.expiration_year.value|default_if_none:"" }}">
                    </div>
                </div>
            </div>
            {% bootstrap_field form.security_code placeholder='Security Code' layout='horizontal' horizontal_label_class="col-lg-3" horizontal_field_class="col-lg-7" %}
            {% bootstrap_field form.password placeholder="(optional, for 3D-Secure/SecureCode)" layout="horizontal" horizontal_label_class="col-lg-3" horizontal_field_class="col-lg-7" %}
        </div>
        <div class="col-12 col-lg-4 g-0 align-items-end">
            <div class="row justify-content-center">
                <div class="card-wrapper"></div>
            </div>
            <div class="row justify-content-center mt-3">
                <span class="small text-center fw-light">
                    <i class="fa fa-lock fa-fw"></i> {% translate "All fields in this section will be stored securely." %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}

{% block additionalJS %}
    {{ block.super }}
    <script>
        window.addEventListener('DOMContentLoaded', () => {
            const card = new Card({
                form: '#ccform',
                container: '.card-wrapper',
                formSelectors: {
                    numberInput: 'input#id_number',
                    expiryInput: 'input#id_expiration_month, input#id_expiration_year',
                    cvcInput: 'input#id_security_code',
                    nameInput: 'input#id_holder',
                },
                messages: {
                    validDate: '{% translate "valid\nthru" %}',
                    monthYear: '{% translate "MM" %}/{% translate "YYYY" %}',
                },
                // width: 200,
                placeholders: {
                    number: '•••• •••• •••• ••••',
                    name: '{% translate "Full name" %}',
                    expiry: '••/••••',
                    cvc: '•••'
                },
            })
        })

        /* Automatically split input into seperate blocks */
        ccNumberField = document.getElementById('id_number')
        ccNumberField.addEventListener('input', (e) => {
            const result = ccNumberField.value.match(/\d{1,4}/g) ?? [];
            ccNumberField.value = result.join(' ')
        })
    </script>
{% endblock %}

teamvault/apps/secrets/templates/secrets/addedit_content/file.html
{% extends "secrets/secret_addedit.html" %}
{% load django_bootstrap5 %}
{% load i18n %}
{% block form_attributes %}enctype="multipart/form-data"{% endblock %}
{% block content_type_fields %}
    <div class="row mb-3 required">
        <label class="col-xl-2 col-form-label form-label securely-saved" for="{{ form.file.id_for_label }}">
            {{ form.file.label }}
        </label>
        <div class="col-xl-8">
            <div class="input-group {% if form.file.errors %}is-invalid{% endif %}">
                <input type="text" class="form-control {% if form.file.errors %}is-invalid{% endif %}" readonly
                       autocomplete="off" id="file-text"
                       placeholder="{% if secret %}{% translate "(unchanged)" %}{% else %}{% translate "No file selected" %}{% endif %}">
                <div class="btn-group">
                    <input id="id_file" name="file" type="file" class="d-none"
                           {% if not secret %}required="required"{% endif %}>
                    <label class="btn btn-outline-accent btn-file" for="id_file">
                        {% translate "Browse..." %}
                    </label>
                </div>
            </div>
            {% for error in form.file.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block additionalJS %}
    {{ block.super }}
    <script>
        window.addEventListener('DOMContentLoaded', () => {
            const fileInput = document.getElementById('id_file')
            const fileNameInput = document.getElementById('file-text')
            fileInput.addEventListener('change', () => {
                fileNameInput.value = fileInput.files[0].name
            })
            window.addEventListener('load', () => {
                /* Set file name even after going back in browser history */
                if (fileInput.files.length === 1) {
                    fileNameInput.value = fileInput.files[0].name
                }
            })
        })
    </script>
{% endblock %}

teamvault/apps/secrets/templates/secrets/addedit_content/password.html
{% extends "secrets/secret_addedit.html" %}
{% load i18n %}
{% load django_bootstrap5 %}
{% block content_type_fields %}
    <div class="row mb-3 {% if not form.password.errors and form.is_bound %}is-valid{% endif %}">
        <div class="col-xl-2">
            <label class="col-form-label securely-saved" for="{{ form.password.id_for_label }}">
                {% translate "Password" %}
            </label>
        </div>
        <div class="col-xl-8">
            <div class="input-group">
                <input class="form-control {% if not form.password.errors and form.is_bound %}is-valid{% endif %}"
                       id="{{ form.password.id_for_label }}" name="{{ form.password.name }}"
                       placeholder="{% if secret %}{% trans "(unchanged)" %}{% else %}**************{% endif %}"
                       {% if not secret %}required="required"{% endif %} type="password" autocomplete="off"
                       {% if form.is_bound and not secret %}value="{{ form.password.value }}"{% endif %}>

                <span class="input-group-text" title="{% trans "Password strength" %}" id="id_password_strength">
                    {% for i in '12345'|make_list %}
                        <i class="far fa-star text-muted"></i>
                    {% endfor %}
                </span>
                <button class="btn border btn-light" id="id_pwgen" type="button"
                        title="{% trans "Generate random password" %}">
                    <i class="fa fa-refresh fa-fw align-middle text-body"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="row {% if form.otp_key_data.errors %}mb-1{% else %}mb-3{% endif %}">
        <div class="col-xl-2">
            <label class="col-form-label securely-saved" for="{{ form.otp_key.id_for_label }}">
                {% translate "OTP secret key" %}
            </label>
        </div>
        <div class="col-xl-8">
            <div class="input-group">
                <input class="form-control {% if form.otp_key_data.errors %}is-invalid{% elif form.is_bound %}is-valid{% endif %}"
                       id="{{ form.otp_key.id_for_label }}" type="text"
                       placeholder="{% if current_revision.otp_key_set %}{% trans "(unchanged)" %}
                                    {% else %}{% trans "enter OTP secret key" %}{% endif %}">
                <input type="hidden" class="form-control" id="{{ form.otp_key_data.id_for_label }}"
                       name="{{ form.otp_key_data.name }}" value="">
                <canvas id="canvas" style="display: none;"></canvas>
                <button class="btn border btn-light" id="key-input-type" type="button"
                        title="{% trans "Switch to enter OTP key as QR image or paste from clipboard" %}"
                        data-bs-toggle="tooltip">
                    <i class="fa fa-qrcode fa-fw align-middle"></i>
                </button>
                {% for text in form.otp_key_data.errors %}
                    <div class="invalid-feedback">{{ text }}</div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% bootstrap_field form.username placeholder="(optional)" layout="horizontal" label_class="searchable" %}
    {% bootstrap_field form.url placeholder="(optional)" layout="horizontal" label_class="searchable" %}
{% endblock %}

{% block additionalJS %}
    {{ block.super }}
    <script>
        const passwordField = document.getElementById('id_password')
        const passwordGeneratorField = document.getElementById('id_pwgen')
        const passwordStrengthField = document.getElementById('id_password_strength')
        const otpField = document.getElementById('{{ form.otp_key.id_for_label }}')
        const otpKeyData = document.getElementById('{{ form.otp_key_data.id_for_label }}')
        const typeBtn = document.getElementById('key-input-type')

        passwordField.generated = false

        function ratePassword() {
            let score = zxcvbn(passwordField.value.toString()).score + 1;
            let color = "text-warning-bright";
            if (!passwordField.value) {
                color = "text-muted";
                score = 0;
            } else if (score <= 2) {
                color = "text-danger-bright";
            } else if (score === 5) {
                color = "text-success-bright";
            }
            var filled_star = `<i class='fas fa-star ${color}'></i>`;
            var hollow_star = `<i class='far fa-star ${color}'></i>`;
            passwordStrengthField.innerHTML = filled_star.repeat(score) + hollow_star.repeat(5 - score)
        }

        async function generatePassword() {
            const source = await fetch('{% url 'api.generate-password' %}');
            return source.json();
        }

        function keyInputText() {
            let typeBtnTooltip = bootstrap.Tooltip.getInstance('#key-input-type')
            typeBtnTooltip.setContent({
                '.tooltip-inner':
                    '{% trans "Switch to enter OTP key as plain text" %}'
            })

            const typeBtn = document.getElementById('key-input-type');
            typeBtn.querySelector('i').classList.remove('fa-qrcode')
            typeBtn.querySelector('i').classList.add('fa-keyboard')
            otpField.title = "Enter OTP key as QR image or paste from clipboard"
            otpField.type = "file"
        }

        function keyInputQr() {
            let typeBtnTooltip = bootstrap.Tooltip.getInstance('#key-input-type')
            typeBtnTooltip.setContent({
                '.tooltip-inner':
                    '{% trans "Switch to enter OTP key as QR image or paste from clipboard" %}'
            })
            const typeBtn = document.getElementById('key-input-type');
            typeBtn.querySelector('i').classList.remove('fa-keyboard')
            typeBtn.querySelector('i').classList.add('fa-qrcode')
            otpField.title = "Enter OTP secret key manually"
            otpField.type = "text"
        }

        document.addEventListener('paste', e => {
            if (otpField.type === "file") {
                otpField.files = e.clipboardData.files;
                otpField.dispatchEvent(new Event('change'));
            }
        })

        document.addEventListener('submit', () => {
            if (otpField.value && !otpKeyData.value) {
                let data = otpField.value;
                if (!data.includes('?secret=')) {
                    data = '?secret=' + data + '&';
                }
                if (!data.includes('digits=')) {
                    data += 'digits=6&';
                }
                if (!data.includes('algorithm=')) {
                    data += 'algorithm=SHA1&';
                }
                otpKeyData.value = data;
            }
        })

        document.addEventListener('DOMContentLoaded', () => {
            ratePassword();
        })

        otpField.addEventListener('change', () => {
            if (otpField.type !== "file") {
                return;
            }
            const file = otpField.files[0];
            if (!file) {
                return;
            }
            const reader = new FileReader();
            reader.onload = function (event) {
                const img = new Image();
                img.onload = function () {
                    const canvas = document.getElementById('canvas');
                    const ctx = canvas.getContext('2d');
                    canvas.width = img.width;
                    canvas.height = img.height;
                    ctx.fillStyle = "rgb(255, 255, 255)"
                    ctx.fillRect(0, 0, canvas.width, canvas.height)
                    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
                    const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
                    try {
                        const code = qrScanner(imageData.data, imageData.width, imageData.height);
                        keyInputQr();
                        let data = new URL(code.data.toString());
                        otpKeyData.value = data;
                        otpField.value = data.searchParams.get('secret');
                    } catch (e) {
                        keyInputText()
                        window.notyf.error("Error. No QR code found. Please try again.")
                    }
                };
                img.src = event.target.result;
            };
            reader.readAsDataURL(file);
        })

        passwordField.addEventListener('keyup', () => {
            ratePassword();
            passwordField.generated = false;
            setTimeout(function () {
                    if (!passwordField.generated) {
                        passwordField.type = 'password'
                    }
                },
                2000
            );
        })
        passwordGeneratorField.addEventListener('focusout', () => {
            setTimeout(
                function () {
                    if (document.activeElement !== passwordField) {
                        passwordField.type = 'password';
                    }
                },
                1000
            )
        })
        passwordGeneratorField.addEventListener('click', async () => {
            passwordField.value = await generatePassword();
            ratePassword();
            passwordField.type = 'text';
            passwordField.generated = true;
        })
        typeBtn.addEventListener("click", () => {
            if (otpField.type === "file") {
                keyInputQr();
            } else {
                keyInputText();
            }
        })
    </script>
{% endblock %}