teamvault/apps/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    get_user_avatar_partial,
    search_user,
    user_activate,
    user_detail,
    user_detail_from_request,
    user_pending_secrets,
    user_pending_secrets_csv,
    user_settings,
    users,
)

urlpatterns = (
    path(
        'login/',
        LoginView.as_view(template_name='accounts/login.html'),
        name='accounts.login',
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='accounts/logout.html'),
        name='accounts.logout',
    ),
    path(
        'users/',
        users,
        name='accounts.user-list',
    ),
    path(
        'users/avatar/',
        get_user_avatar_partial,
        name='accounts.user.avatar',
    ),
    path(
        'users/detail/',
        user_detail_from_request,
        name='accounts.user-detail-from-request',
    ),
    path(
        'users/search/',
        search_user,
        name='accounts.search-user',
    ),
    path(
        'users/<str:username>/',
        user_detail,
        name='accounts.user-detail',
    ),
    path(
        'users/<str:username>/pending-secrets/',
        user_pending_secrets,
        name='accounts.user-pending-secrets',
    ),
    path(
        'users/<str:username>/pending-secrets/csv/',
        user_pending_secrets_csv,
        name='accounts.user-pending-secrets-csv',
    ),
    path(
        'users/<str:username>/reactivate',
        user_activate,
        name='accounts.user-reactivate',
    ),
    path(
        'users/<str:username>/deactivate',
        user_activate,
        {'deactivate': True},
        name='accounts.user-deactivate',
    ),
    path(
        'settings/',
        user_settings,
        name='accounts.user-settings',
    ),
)

teamvault/urls.py
from django.conf.urls import include
from django.urls import path

handler404 = 'teamvault.views.handler404'

urlpatterns = (
    path('api/', include('teamvault.apps.secrets.api.urls'), name='api'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('audit', include('teamvault.apps.audit.urls'), name='audit'),
    path('', include('teamvault.apps.secrets.urls'), name='secrets'),
    path('', include('teamvault.apps.accounts.urls'), name='accounts'),
    path('', include('social_django.urls', namespace='social')),
)

teamvault/apps/accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser, Group
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    # TODO: Merge this with UserProfile model
    entry_uuid = models.CharField(max_length=36, default='', blank=True)


class UserProfile(models.Model):
    # Since our static files are not served by some webserver but by TeamVault (/Whitenoise) directly
    # to keep the installation overhead low, we'd have to do the same thing with media files.
    # Static files will get replaced with each teamvault deployment, media files should not.
    # Because of that, we'd have to make admins configure a persistent directory for them.
    # For now, that trade-off is not worth it, so let's store avatars as binary data, instead.
    avatar = models.BinaryField(blank=True, null=True)
    default_sharing_groups = models.ManyToManyField(
        Group,
        blank=True,
        help_text=_('New secrets created by you will be shared with these groups.'),
        related_name='+',
    )
    hide_deleted_secrets = models.BooleanField(
        default=True, help_text=_('Hides deleted secrets per default. Enable them in filters to see them again.')
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')

teamvault/apps/accounts/forms.py
from django import forms

from teamvault.apps.accounts.models import UserProfile


class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['default_sharing_groups'].queryset = self.fields['default_sharing_groups'].queryset.order_by('name')

    class Meta:
        fields = ['default_sharing_groups', 'hide_deleted_secrets']
        model = UserProfile

teamvault/apps/accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db import transaction
from django.db.models import Q
from django.http import (
    HttpResponseBadRequest,
    HttpResponseRedirect,
    JsonResponse,
)
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import require_http_methods
from django.views.generic import DetailView, ListView, UpdateView

from teamvault.apps.secrets.enums import SecretStatus
from .forms import UserProfileForm
from .models import UserProfile as UserProfileModel
from ..audit.auditlog import log
from ..audit.models import AuditLogCategoryChoices
from ..secrets.models import SecretRevision

User = get_user_model()


class UserProfile(UpdateView):
    form_class = UserProfileForm
    model = UserProfileModel
    template_name = 'accounts/user_settings.html'
    success_url = reverse_lazy('accounts.user-settings')

    def get_object(self, *args, **kwargs):  # noqa: ARG002
        return UserProfileModel.objects.get_or_create(user=self.request.user)[0]

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _('Successfully updated settings.'))
        return response


user_settings = login_required(UserProfile.as_view())


class UserList(ListView):
    context_object_name = 'users'
    model = User
    paginate_by = 25
    template_name = 'accounts/user_list.html'

    def get_queryset(self):
        return self.model.objects.order_by('username')


users = user_passes_test(lambda u: u.is_superuser)(UserList.as_view())


class UserDetail(DetailView):
    context_object_name = 'user'
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name = 'accounts/user_detail.html'


user_detail = user_passes_test(lambda u: u.is_superuser)(UserDetail.as_view())


@user_passes_test(lambda u: u.is_superuser)
def user_detail_from_request(request):
    username = request.GET.get('username', '').strip()
    if not username:
        return HttpResponseBadRequest(_('Username is required'))
    user = get_object_or_404(User, username=username)
    return HttpResponseRedirect(reverse('accounts.user-detail', kwargs={'username': user}))


@user_passes_test(lambda u: u.is_superuser)
@require_http_methods(['POST'])
def user_activate(request, username, deactivate=False):
    user = get_object_or_404(
        User,
        username=username,
        is_active=deactivate,
    )
    user.is_active = not deactivate
    user.save()
    if deactivate:
        user.groups.clear()
        accessed_revs = (
            SecretRevision.objects
            .filter(
                accessed_by=user,
            )
            .exclude(
                secret__needs_changing_on_leave=False,
            )
            .exclude(secret__status=SecretStatus.NEEDS_CHANGING)
            .select_related(
                'secret',
            )
        )
        secrets = set()
        for rev in accessed_revs:
            if rev.is_current_revision:
                secrets.add(rev.secret)
        with transaction.atomic():
            for secret in secrets:
                secret.status = SecretStatus.NEEDS_CHANGING
                secret.save()
                msg = _("secret '{secret}' needs changing because user '{user}' was deactivated").format(
                    secret=secret.name,
                    user=user.username,
                )
                log(
                    msg,
                    actor=request.user,
                    category=AuditLogCategoryChoices.USER_DEACTIVATED,
                    secret=secret,
                    user=user,
                )
        log(
            _('{actor} deactivated {user}, {secrets} secrets marked for changing').format(
                actor=request.user.username,
                user=user.username,
                secrets=len(secrets),
            ),
            actor=request.user,
            category=AuditLogCategoryChoices.USER_DEACTIVATED,
            user=user,
        )
    else:
        log(
            _('{actor} reactivated {user}').format(
                actor=request.user.username,
                user=user.username,
            ),
            actor=request.user,
            category=AuditLogCategoryChoices.USER_ACTIVATED,
            user=user,
        )
    return HttpResponseRedirect(reverse('accounts.user-detail', kwargs={'username': user.username}))


def search_user(request):
    if not request.user.is_superuser:
        return {}
    q = request.GET.get('q', '').strip()
    if not q:
        return {}
    users_queryset = User.objects.filter(
        Q(username__icontains=q) | Q(first_name__icontains=q) | Q(last_name__icontains=q)
    )[:15]
    results: list[dict[str, str]] = [
        {
            'username': user.username,
            'cn': f'{user.first_name} {user.last_name}'.strip(),
        }
        for user in users_queryset
    ]
    return JsonResponse({'results': results})


def get_user_avatar_partial(request):
    if not request.user.is_superuser:
        return {}
    username = request.GET.get('username', '').strip()
    if not username:
        return {}
    user = User.objects.get(username=username)
    return render(request, 'accounts/_avatar.html', {'user': user, 'tooltip_title': username})

teamvault/apps/accounts/templates/accounts/_avatar.html
{% if user.profile.avatar %}
    <img src="data: image/jpeg; base64,{{ user.profile.avatar.decode }}" alt="{{ user.username }} avatar"
         class="avatar {{ classes }}"
            {% if tooltip_title %}
         data-bs-toggle="tooltip"
         data-bs-placement="top"
         data-bs-title="{{ tooltip_title }}"
            {% endif %}
    >
{% elif user.first_name and user.last_name %}
    <svg xmlns="http://www.w3.org/2000/svg" class="avatar {{ classes }}"
            {% if tooltip_title %}
         data-bs-toggle="tooltip"
         data-bs-placement="top"
         data-bs-title="{{ tooltip_title }}"
            {% endif %}
    >
        <text x="50%" y="50%" dy=".1em" fill="#fff" text-anchor="middle" dominant-baseline="middle">
            {{ user.first_name.0.capitalize }}{{ user.last_name.0.capitalize }}
        </text>
    </svg>
{% else %}
    <div class="rounded-circle border border-5" style="background-color: var(--bs-border-color)">
        <i class="fa fa-user-secret fa-lg fa-fw lh-1"></i>
    </div>
{% endif %}

teamvault/apps/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block navbar %}{% endblock %}
{% block title %}{% trans "Login" %}{% endblock %}
{% block super_content %}
    <div class="d-flex justify-content-center align-items-center vh-100">
        <form id="loginform" class="text-center border rounded-5 bg-body shadow p-5" role="form" method="POST" style="width: 25rem">
            {% csrf_token %}
            <div class="mb-5">
                <span class="fs-1 text-body">Team</span><span class="fs-1 text-accent">Vault</span>
            </div>
            {% if form.errors %}
                <p class="alert alert-danger text-break">{% trans "Your username and password didn't match. Please try again." %}</p>
            {% endif %}
            <div class="mb-2">
                <input type="text" name="username" class="form-control" placeholder="{% trans "Username" %}"
                       autocomplete="username" required autofocus>
            </div>
            <div class="mb-3">
                <div class="input-group">
                    <input type="password" name="password" class="form-control" placeholder="{% trans "Password" %}"
                           autocomplete="current-password" required>
                    <button form="loginform" class="btn btn-outline-accent" type="submit"><i
                            class="fa fa-chevron-right"></i></button>
                </div>
            </div>
            {% if google_auth_enabled %}
                <p class="text-center">{% trans "or" %}</p>
                <div class="d-grid">
                    <a class="btn btn-outline-accent btn-lg"
                       href="{% url "social:begin" "google-oauth2" %}?{{ request.GET.urlencode }}">
                        <i class="fa-brands fa-google"></i> &nbsp;
                        {% trans "Sign in with Google" %}
                    </a>
                </div>
            {% endif %}
        </form>
    </div>
{% endblock %}
{% block footer %}{% endblock %}

teamvault/apps/accounts/templates/accounts/logout.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block navbar %}{% endblock %}
{% block title %}{% trans "Logout" %}{% endblock %}

{% block super_content %}
    <div class="d-flex justify-content-center align-items-center vh-100">
        <div class="text-center border rounded-5 bg-body shadow p-5" style="width: 25rem">
            <div class="mb-2">
                <span class="fs-1 text-body ">Team</span><span class="fs-1 text-accent">Vault</span>
            </div>
            <div class="mb-4">
                <span>{% trans "Logged out." %}</span>
            </div>
            <a href="{% url 'accounts.login' %}">{% trans "Log in again?" %}</a>
        </div>
    </div>
{% endblock %}
{% block footer %}{% endblock %}

teamvault/apps/accounts/templates/accounts/user_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Manage user" %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{% trans "Manage user" %}</h1>
                <br><br>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <table class="table table-hover mb-0">
                        <tr>
                            <td>{% trans "Username" %}</td>
                            <td>{{ user.username }}</td>
                        </tr>
                        <tr>
                            <td>{% trans "Email" %}</td>
                            <td>{{ user.email }}</td>
                        </tr>
                        <tr>
                            <td>{% trans "Created" %}</td>
                            <td>{{ user.date_joined|date:"Y-m-d H:i:s e" }}</td>
                        </tr>
                        <tr>
                            <td>{% trans "Last login" %}</td>
                            <td>{{ user.last_login|date:"Y-m-d H:i:s e" }}</td>
                        </tr>
                        <tr>
                            <td>{% trans "Groups" %}</td>
                            <td>
                                {% for group in user.groups.all|dictsort:"name" %}
                                    {{ group.name }}<br>
                                {% endfor %}
                            </td>
                        </tr>
                    </table>
                </div>
            </div>

            <div class="col-md-4 mt-md-0 mt-3">
                <div class="mb-3">
                    <a href="{% url 'audit.log' %}?actor={{ user.username }}" class="btn btn-lg btn-light">
                        <i class="fa fa-address-card fa-fw" aria-hidden="true"></i>
                        {% trans "View audit log" %}
                    </a>
                </div>
                <div>
                    {% if user.is_active %}
                        <button type="button" class="btn btn-danger btn-lg" data-bs-toggle="modal"
                                data-bs-target="#modal-deactivate">
                            <i class="fa fa-lock fa-fw"></i>
                            {% trans "Deactivate" %}
                        </button>
                    {% else %}
                        <button type="button" class="btn btn-success btn-lg" data-bs-toggle="modal"
                                data-bs-target="#modal-reactivate">
                            <i class="fa fa-lock-open fa-fw"></i>
                            {% trans "Reactivate" %}
                        </button>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if not user.is_active %}
            <div id="secrets-load-container" class="mt-4"
                 hx-get="{% url 'accounts.user-pending-secrets' user.username %}"
                 hx-trigger="load" hx-swap="outerHTML">
                <div class="text-center p-5 card">
                    <div class="card-body">
                        <i class="fa fa-spinner fa-spin fa-2x text-muted mb-2"></i>
                        <p>{% trans "Loading secrets and checking permissions..." %}</p>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>

    <div class="modal fade" id="universal-share-modal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl">
            <div id="modal-content-target" class="modal-content">
            </div>
        </div>
    </div>

    {% if user.is_active %}
        <div class="modal fade" id="modal-deactivate" tabindex="-1" role="dialog"
             aria-labelledby="modal-deactivate-label"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="modal-deactivate-label">{% trans "Confirm deactivation" %}</h4>
                        <button type="button" class="btn-close fa-pull-right" data-bs-dismiss="modal"
                                aria-label="Close"></button>
                    </div>
                    <form role="form" method="POST"
                          action="{% url 'accounts.user-deactivate' username=user.username %}">
                        {% csrf_token %}
                        <div class="modal-body">
                            <div class="alert alert-warning">
                                <i class="fa fa-info-circle fa-fw"></i>
                                {% trans "Any secrets accessed by this user will be marked for changing." %}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-danger"><i
                                    class="fa fa-lock fa-fw"></i> {% trans "Deactivate" %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        <div class="modal fade" id="modal-reactivate" tabindex="-1" role="dialog"
             aria-labelledby="modal-reactivate-label"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="modal-reactivate-label">{% trans "Confirm reactivation" %}</h4>
                        <button type="button" class="btn-close fa-pull-right" data-bs-dismiss="modal"
                                aria-label="Close"></button>
                    </div>
                    <form role="form" method="POST"
                          action="{% url 'accounts.user-reactivate' username=user.username %}">
                        {% csrf_token %}
                        <div class="modal-body">
                            <div class="alert alert-info">{% trans "Do you really wish to reactivate this user?" %}</div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success"><i
                                    class="fa fa-lock-open fa-fw"></i> {% trans "Reactivate" %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

teamvault/apps/accounts/templates/accounts/user_list.html
{% extends "base.html" %}
{% load i18n %}
{% load smart_pagination %}
{% block title %}{% trans "Users" %}{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="row d-flex justify-content-between">
                <div class="col">
                    <h1 class="h1">
                        {% trans "Users" %}
                    </h1>
                </div>
                <div class="col text-end align-self-center ps-3">
                    <div class="usersearch d-flex align-items-center border border-2 rounded-3 ps-3"
                         data-target="#user-list-search" tabindex="0" role="search" id="usersearch-div">
                        <label for="user-list-search">
                            <i class="fa fa-search search-icon" aria-hidden="true"></i>
                        </label>
                        <select id="user-list-search" type="text" class="form-control"
                                placeholder="Search user...">
                        </select>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-body table-responsive">
                    <table class="table table-hover">
                        <tr>
                            <th>{% trans "Username" %}</th>
                            <th>{% trans "Email" %}</th>
                            <th>{% trans "Active" %}</th>
                            <th>{% trans "Admin" %}</th>
                            <th>{% trans "Last login" %}</th>
                        </tr>
                        {% for user in users %}
                            <tr>
                                <td>
                                    <a href="{% url 'accounts.user-detail' username=user.username %}">{{ user.username }}</a>
                                </td>
                                <td>
                                    <a href="{% url 'accounts.user-detail' username=user.username %}">{{ user.email }}</a>
                                </td>
                                <td>
                                    {% if user.is_active %}
                                        <i class="fa fa-check text-success-bright"></i>
                                    {% else %}
                                        <i class="fa fa-times text-danger-bright"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if user.is_superuser %}
                                        <i class="fa fa-check text-success-bright"></i>
                                    {% else %}
                                        <i class="fa fa-times text-danger-bright"></i>
                                    {% endif %}
                                </td>
                                <td>{{ user.last_login|date:"Y-m-d H:i:s e" }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
            {% include "pagination.html" %}
        </div>
    </div>
{% endblock %}
{% block additionalJS %}
    <script>
        const userUrl = '{% url "accounts.search-user" %}'
        const avatarUrl = '{% url "accounts.user.avatar" %}'
        var ts = new TomSelect('#user-list-search', {
            closeAfterSelect: true,
            create: false,
            dropdownParent: '#usersearch-div',
            labelField: 'username',
            maxItems: 1,
            openOnFocus: false,
            searchField: ['username', 'cn'],
            valueField: 'username',
            load: function (query, callback) {
                if (!query) return callback();
                const params = new URLSearchParams({
                    q: query,
                });
                fetch(`${userUrl}?${params.toString()}`)
                    .then(res => res.json())
                    .then(json => callback(json.results))
                    .catch(() => callback());
            },
            onLoad: function () {
                const dropdownEl = this.dropdown;
                htmx.process(dropdownEl);
            },
            render: {
                option(data, escape) {
                    return `<div class="row align-items-center justify-between">
                                <div class="col-auto d-flex justify-content-center justify-content-lg-end align-items-center">
                                   <span id="avatar-span-${escape(data.username)}">
                                       <div class="avatar-container me-2" hx-get="${avatarUrl}?username=${escape(data.username)}"
                                            hx-target="this"
                                            hx-swap="innerHTML"
                                            hx-trigger="load">
                                       </div>
                                   </span
                                </div>
                                <div class="col-auto ts-option-name-field">${escape(data.cn)}</div>
                            </div>`;
                },
                item(data, escape) {
                    return `<div>${escape(data.cn)}</div>`;
                }
            }
        });

        ts.on('item_add', (value) => {
            window.location.href = `{% url 'accounts.user-detail-from-request' %}?username=${value}`;
        });

        const userSearchBar = document.getElementById('usersearch-div');
        const inputEl = userSearchBar.children[2].children[0].children[0]
        userSearchBar.addEventListener('click', _ => {
            if (document.activeElement === inputEl) return;
            inputEl.focus();
        })
    </script>

{% endblock %}

teamvault/apps/accounts/templates/accounts/user_settings.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}
{% block title %}{% translate "Settings" %}{% endblock %}
{% block content %}
    <div class="container-xxl">
        <h2 class="mb-3">{% translate "Settings" %}</h2>
        <div class="card">
            <div class="card-body mx-5 mt-4 mb-3">
                <form role="form" method="POST" action="{% url "accounts.user-settings" %}">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col-11">
                            {% bootstrap_field form.default_sharing_groups label_class="h5" %}
                        </div>
                    </div>
                    {% bootstrap_field form.hide_deleted_secrets checkbox_style="switch" %}
                    <button type="submit" class="btn btn-outline-accent px-3 mt-3">
                        {% translate "Save" %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block additionalJS %}
    <script>
        $('#id_default_sharing_groups').select2()
    </script>
{% endblock %}