teamvault/apps/audit/urls.py
from django.urls import path

from . import views

urlpatterns = (
    path(
        'log/',
        views.auditlog,
        name='audit.log',
    ),
)

teamvault/urls.py
from django.conf.urls import include
from django.urls import path

handler404 = 'teamvault.views.handler404'

urlpatterns = (
    path('api/', include('teamvault.apps.secrets.api.urls'), name='api'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('audit', include('teamvault.apps.audit.urls'), name='audit'),
    path('', include('teamvault.apps.secrets.urls'), name='secrets'),
    path('', include('teamvault.apps.accounts.urls'), name='accounts'),
    path('', include('social_django.urls', namespace='social')),
)

teamvault/apps/audit/models.py
from django.conf import settings
from django.db import models
from django.db.models import TextChoices
from django.utils.translation import gettext_lazy as _


class AuditLogCategoryChoices(TextChoices):
    SECRET_READ = 'secret_read', _('secret_read')
    SECRET_ELEVATED_SUPERUSER_READ = 'secret_elevated_superuser_read', _('secret_elevated_superuser_read')
    SECRET_PERMISSION_VIOLATION = 'secret_permission_violation', _('secret_permission_violation')
    SECRET_CHANGED = 'secret_changed', _('secret_changed')
    SECRET_METADATA_CHANGED = 'secret_metadata_changed', _('secret_metadata_changed')
    SECRET_RESTORED = 'secret_restored', _('secret_restored')
    SECRET_NEEDS_CHANGING_REMINDER = 'secret_needs_changing_reminder', _('secret_needs_changing_reminder')
    SECRET_SHARED = 'secret_shared', _('secret_shared')
    SECRET_SUPERUSER_SHARED = 'secret_superuser_shared', _('secret_superuser_shared')
    SECRET_SHARE_REMOVED = 'secret_share_removed', _('secret_share_removed')
    SECRET_SUPERUSER_SHARE_REMOVED = 'secret_superuser_share_removed', _('secret_superuser_share_removed')
    SECRET_ACCESS_REQUEST = 'secret_legacy_access_requests', _('secret_legacy_access_requests')

    USER_ACTIVATED = 'user_activated', _('user_activated')
    USER_DEACTIVATED = 'user_deactivated', _('user_deactivated')
    USER_SETTINGS_CHANGED = 'user_settings_changed', _('user_settings_changed')

    SHARE_AUTOMATICALLY_REVOKED = 'share_automatically_revoked', _('share_automatically_revoked')

    MISCELLANEOUS = 'miscellaneous', _('miscellaneous')
    DATA_EXPORT = 'data_export', _('data_export')


class LogEntry(models.Model):
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        models.PROTECT,
        blank=True,
        null=True,
        related_name='logged_actions',
    )
    category = models.CharField(
        choices=AuditLogCategoryChoices.choices,
        default=AuditLogCategoryChoices.MISCELLANEOUS,
        max_length=64,
    )
    group = models.ForeignKey(
        'auth.Group',
        models.PROTECT,
        blank=True,
        null=True,
        related_name='logged_actions',
    )
    message = models.TextField()
    reason = models.TextField(  # noqa: DJ001
        blank=True,
        null=True,
    )
    secret = models.ForeignKey(
        'secrets.Secret',
        models.PROTECT,
        blank=True,
        null=True,
        related_name='logged_actions',
    )
    secret_revision = models.ForeignKey(
        'secrets.SecretRevision',
        models.PROTECT,
        blank=True,
        null=True,
        related_name='logged_actions',
    )
    time = models.DateTimeField(
        auto_now_add=True,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        models.PROTECT,
        blank=True,
        null=True,
        related_name='affected_by_actions',
    )

    class Meta:
        indexes = [
            models.Index(fields=['category'], name='logentry_category_idx'),
            models.Index(fields=['time'], name='logentry_time_idx'),
            models.Index(fields=['category', 'time'], name='logentry_category_time_idx'),
            models.Index(fields=['actor'], name='logentry_actor_idx'),
            models.Index(fields=['group'], name='logentry_group_idx'),
            models.Index(fields=['secret'], name='logentry_secret_idx'),
            models.Index(fields=['user'], name='logentry_user_idx'),
        ]
        ordering = ('-time',)

teamvault/apps/audit/views.py
from django.contrib.auth.decorators import user_passes_test
from django.db.models import Q
from django.views.generic import ListView

from .filters import AuditLogFilter
from .models import LogEntry
from ..secrets.models import Secret
from ...views import FilterMixin, PageSizeMixin


class LogEntryList(PageSizeMixin, ListView, FilterMixin):
    filter = None
    filter_class = AuditLogFilter
    context_object_name = 'log_entries'
    paginate_by = 25
    template_name = 'audit/log.html'

    def get_queryset(self):
        queryset = LogEntry.objects.all()
        if 'search' in self.request.GET:
            query = self.request.GET['search']
            queryset = queryset.filter(Q(actor__icontains=query) | Q(message__icontains=query))

        return self.get_filtered_queryset(queryset)

    @staticmethod
    def manipulate_filter_form(bound_data, filter_form):
        # Set queryset since we'll retrieve choices via ajax and need to show the initial one
        if bound_data.get('secret'):
            secret_choices = Secret.objects.filter(pk=bound_data['secret'].pk)
        else:
            secret_choices = Secret.objects.none()
        filter_form.fields['secret'].queryset = secret_choices
        return filter_form


auditlog = user_passes_test(lambda u: u.is_superuser)(LogEntryList.as_view())

teamvault/apps/audit/templates/audit/log.html
{% extends "base.html" %}
{% load humanize %}
{% load i18n %}
{% load static %}
{% load smart_pagination %}
{% block title %}{% trans "Audit log" %}{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10">
            <div class="row mb-3">
                <h2>
                    {% translate "Audit log" %}
                </h2>
            </div>
            <div class="m-2">
                {% include 'helpers/filter.html' %}
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body table-responsive">
                            <table class="table table-hover">
                                <thead class="fs-5">
                                <tr>
                                    <td>{% translate "Time" %}</td>
                                    <td>{% translate "Actor" %}</td>
                                    <td>{% translate "User" %}</td>
                                    <td>{% translate "Secret" %}</td>
                                    <td>{% translate "Message" %}</td>
                                    <td>{% translate "Category" %}</td>
                                </tr>
                                </thead>
                                <tbody>
                                {% for entry in log_entries %}
                                    <tr>
                                        <td>{{ entry.time|date:"Y-m-d H:i:s e" }}</td>
                                        <td>{% if entry.actor %}{{ entry.actor.username }}{% endif %}</td>
                                        <td>{{ entry.user|default_if_none:'' }}</td>
                                        <td>{% if entry.secret %}
                                            <a href="{{ entry.secret.get_absolute_url }}">{{ entry.secret.name }}</a>{% endif %}
                                        </td>
                                        <td>
                                            {{ entry.message }}
                                            {% if entry.reason %}
                                                <br>{% translate "Reason" %}: {{ entry.reason }}
                                            {% endif %}
                                        </td>
                                        <td>{{ entry.category }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            {% include "pagination.html" %}
        </div>
    </div>
{% endblock %}

{% block additionalJS %}
    <script>
        $("#id_actor").select2({
            dropdownParent: document.getElementById('filter-modal'),
            placeholder: "{% translate "Actor" %}",
            allowClear: true,
        });
        $("#id_user").select2({
            dropdownParent: document.getElementById('filter-modal'),
            placeholder: "{% translate "User" %}",
            allowClear: true,
        });
        $("#id_secret").select2({
            dropdownParent: document.getElementById('filter-modal'),
            multiple: false,
            placeholder: "{% translate "Secret" %}",
            allowClear: true,
            delay: 250,
            minimumInputLength: 3,
            ajax: {
                url: '{% url "secrets.secret-search" %}',
                dataType: "json",
                data: function ({term}) {
                    return {
                        q: term
                    };
                },
                processResults: function (data) {
                    let results = []
                    data.results.forEach(item => results.push({
                        id: item['hashid'],
                        text: item['name']
                    }))
                    return {
                        count: data.count,
                        results: results
                    };
                }
            }
        });
    </script>
{% endblock %}